export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const ADD_LOGIN_REQUEST = "ADD_LOGIN_REQUEST";
export const ADD_LOGIN_SUCCESS = "ADD_LOGIN_SUCCESS";
export const ADD_LOGIN_FAILURE = "ADD_LOGIN_FAILURE";
